# Site settings
title: From the desk of Scott Thornton
email: 
description: >-
  Deep dives into AI/ML, Security, Networking, and Programming. 
  Tutorials, demos, and practical insights from hands-on experience.
baseurl: ""
url: "https://scthornton.github.io"
author: Scott Thornton
github_username: scthornton
linkedin_username: scthornton

# Build settings
markdown: kramdown
highlighter: rouge
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-remote-theme


# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Collections
collections:
  tutorials:
    output: true
    permalink: /tutorials/:title/
    sort_by: date
    order: descending
  cheatsheets:
    output: true
    permalink: /cheatsheets/:title/
  demos:
    output: true
    permalink: /demos/:title/

# Category descriptions
category_descriptions:
  ai-ml:
    name: "AI & Machine Learning"
    description: "Deep learning, neural networks, LLMs, and ML engineering"
    icon: "🤖"
  security:
    name: "Security"
    description: "Network, AI, Cloud, Application"
    icon: "🔒"
  networking:
    name: "Networking"
    description: "Architecture, Design, Impementation, and Troubleshooting"
    icon: "🌐"
  python:
    name: "Programming"
    description: "Python, Terraform, useful scripts, programs, projects, and best practices"
    icon: "🐍"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
      type: "tutorials"
    values:
      layout: "tutorial"
      toc: true
  - scope:
      path: ""
      type: "cheatsheets"
    values:
      layout: "cheatsheet"
  - scope:
      path: ""
      type: "demos"
    values:
      layout: "demo"

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
  - setup-blog.sh
